name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
  push:
    paths:
      - wordle-web/**
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        name: Checkout Code
      - uses: actions/setup-node@v3
        name: Setup node
        with:
          node-version: 18
      - run: npm ci
        working-directory: ./wordle-web
        name: npm ci
      - run: npm run lint
        working-directory: ./wordle-web
        name: Lint Code
      - run: npm run format-check
        working-directory: ./wordle-web
        name: Prettier Check
      - run: npm run build
        working-directory: ./wordle-web
      - run: npm run test:unit
        working-directory: ./wordle-web
        name: Run Vitest Unit Tests
        
        # Only Deploy when pushing to main
      - name: Deploy
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_POND_0771E721E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/wordle-web/dist" # App source code path
          skip_app_build: true
          output_location: ""
          api_location: "" # Api source code path - optional
          ###### End of Repository/Build Configurations ######
